# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestAT00 < Formula
  desc "Outputs the test lines of its input"
  homepage "https://github.com/ro-tex/test"
  version "0.0.14"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ro-tex/test/releases/download/v0.0.14/test_0.0.14_darwin_arm64.tar.gz"
      sha256 "1ab710d921990126b563ba5bf36a5c66041fe5ccb8f612e43f2b79d04006a7fb"

      def install
        bin.install "test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ro-tex/test/releases/download/v0.0.14/test_0.0.14_darwin_amd64.tar.gz"
      sha256 "bd6e7a4eddd7f0a4eb1e7ac9f0bcac2ccc1bc2f26f1483a562fdf7f6c183d5ca"

      def install
        bin.install "test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ro-tex/test/releases/download/v0.0.14/test_0.0.14_linux_amd64.tar.gz"
      sha256 "1e674d993bc138e822b8008b80f1ac63d74dd6d5fcea3d237adccfac652f4fdb"

      def install
        bin.install "test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ro-tex/test/releases/download/v0.0.14/test_0.0.14_linux_arm64.tar.gz"
      sha256 "30ea796d96536e060b9261651f178628dca12a3aff83f6ba87a50f05a5788313"

      def install
        bin.install "test"
      end
    end
  end
end
